Update aquasec-push-req.yml
Release Artifacts

diff --git a/.github/workflows/aquasec-push-req.yml b/.github/workflows/aquasec-push-req.yml
--- a/.github/workflows/aquasec-push-req.yml
+++ b/.github/workflows/aquasec-push-req.yml
@@ -25,3 +25,20 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
           TRIVY_RUN_AS_PLUGIN: 'aqua'
           # For http/https proxy configuration add env vars: HTTP_PROXY/HTTPS_PROXY, CA-CRET (path to CA certificate)
+      - name: Manifest Generation
+        run: |
+          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
+          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
+          if ! cat install.sh.checksum | shasum -a 256 ; then
+            echo "install.sh checksum failed"
+            exit 1
+          fi
+          sh install.sh
+          rm install.sh install.sh.checksum
+          billy generate \
+              --access-token "${{ secrets.GITHUB_TOKEN }}" \
+              --aqua-key "${{ secrets.AQUA_KEY }}" \
+              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
+              --artifact-path "stalibali/graphqlliveview:${{ github.sha }}" \
+              --report-format sbom \
+              --sbom-path sbom.cdx.json
